// <auto-generated />
namespace GrdPoc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class droped_ServiceContractViewModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(droped_ServiceContractViewModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201703212119188_droped_ServiceContractViewModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
