// <auto-generated />
namespace GrdPoc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_invoice_tables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_invoice_tables));
        
        string IMigrationMetadata.Id
        {
            get { return "201703291042360_added_invoice_tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
